apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: traces
spec:
  image: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:0.75.0
  mode: deployment
  config: |
    receivers:
      zipkin:
      otlp:
        protocols:
          grpc:
          http:

    processors:
      batch:
      memory_limiter:
        check_interval: 1s
        limit_percentage: 50
        spike_limit_percentage: 30
    
    exporters:
      logging:
      otlp:
        endpoint: "http://tempo.lgtm.svc.cluster.local:4317"
        tls:
          insecure: true
    
    service:
      pipelines:
        traces:
          receivers: [otlp, zipkin]
          processors: [memory_limiter, batch]
          exporters: [otlp, logging]
