# nonk8s
apiVersion: skaffold/v4beta10
kind: Config
metadata:
  name: vulnerabilitytracer
build:
  local:
    useBuildkit: true
  artifacts:
    - image: vulnerabilitytracer-coordinator
      context: .
      docker:
        target: coordinator-runtime
        dockerfile: Dockerfile-vulnerabilitytracer
    - image: vulnerabilitytracer-manager
      context: .
      docker:
        target: manager-runtime
        dockerfile: Dockerfile-vulnerabilitytracer
    - image: vulnerabilitytracer-tracecollector
      context: .
      docker:
        target: tracecollector-runtime
        dockerfile: Dockerfile-vulnerabilitytracer
    - image: vulnerabilitytracer-traceprocessor
      context: .
      docker:
        target: traceprocessor-runtime
        dockerfile: Dockerfile-vulnerabilitytracer
    - image: vulnerabilitytracer-dashboard
      context: .
      docker:
        dockerfile: Dockerfile-dashboard
manifests:
  kustomize:
    paths:
      - kube-manifests/vulnerabilitytracer
      - vulnerabilitytracer-service/db
deploy:
  # Necessary since the inital run of vulnerability tracer pods fails with "connection refused" error
  # when trying to connect to the database
  tolerateFailuresUntilDeadline: true
  statusCheckDeadlineSeconds: 300
  kubectl: {}