# nonk8s
apiVersion: skaffold/v3
kind: Config
metadata:
  name: thesis-project
build:
  local:
    useBuildkit: true
  artifacts:
    - image: thesis-microservice
      context: microservice
manifests:
  kustomize:
    paths:
      - kube-manifests
deploy:
  kubectl: {}
