# nonk8s
apiVersion: skaffold/v3
kind: Config
metadata:
  name: microservices
build:
  local:
    useBuildkit: true
  artifacts:
    - image: thesis-microservice
      context: .
manifests:
  kustomize:
    paths:
      - kube-manifests/microservices
deploy:
  kubectl: {}