# nonk8s
apiVersion: skaffold/v3
kind: Config
metadata:
  name: opentelemetry
build:
  local:
    useBuildkit: true
  artifacts:
    - image: vulnerabilitytracer-javaagent
      context: .
      docker:
        target: javaagentfinal
manifests:
  kustomize:
    paths:
      - kube-manifests/opentelemetry
deploy:
  kubectl: {}
resourceSelector:
  allow:
    - groupKind: "Instrumentation.opentelemetry.io"
      image: [".*"]
      labels: [".*"]