# nonk8s
apiVersion: skaffold/v3
kind: Config
metadata:
  name: microservices
build:
  local:
    useBuildkit: true
  artifacts:
    - image: downstream-caller-service
      context: .
      docker:
        target: downstreamcallerservice
    - image: generator-service
      context: .
      docker:
        target: generatorservice
    - image: loadgenerator
      context: loadgenerator

deploy:
  kubectl: {}

profiles:
  # Qualitative evaluation scenarios
  - name: qualitative-scenario1
    manifests:
      kustomize:
        paths:
          - kube-manifests/qualitative_evaluation/scenario1
  - name: qualitative-scenario2
    manifests:
      kustomize:
        paths:
          - kube-manifests/qualitative_evaluation/scenario2
  - name: qualitative-scenario3
    manifests:
      kustomize:
        paths:
          - kube-manifests/qualitative_evaluation/scenario3
  # Quantitative evaluation scenarios
  - name: quantitative-scenario1
    manifests:
      kustomize:
        paths:
          - kube-manifests/quantitative_evaluation/scenario1
  - name: quantitative-scenario2
    manifests:
      kustomize:
        paths:
          - kube-manifests/quantitative_evaluation/scenario2
  - name: quantitative-scenario3
    manifests:
      kustomize:
        paths:
          - kube-manifests/quantitative_evaluation/scenario3
  - name: quantitative-scenario4
    manifests:
      kustomize:
        paths:
          - kube-manifests/quantitative_evaluation/scenario4
  - name: quantitative-scenario5
    manifests:
      kustomize:
        paths:
          - kube-manifests/quantitative_evaluation/scenario5
  - name: quantitative-scenario6
    manifests:
      kustomize:
        paths:
          - kube-manifests/quantitative_evaluation/scenario6