# nonk8s
apiVersion: skaffold/v3
kind: Config
metadata:
  name: vulnerabilitytracer
build:
  local:
    useBuildkit: true
  artifacts:
    - image: vulnerabilitytracer-api
      context: vulnerabilitytracer-service
      docker:
        target: api-runtime
    - image: vulnerabilitytracer-dashboard
      context: vulnerabilitytracer-dashboard
manifests:
  kustomize:
    paths:
      - kube-manifests/vulnerabilitytracer
      - vulnerabilitytracer-service/db
deploy:
  kubectl: {}