# nonk8s
apiVersion: skaffold/v3
kind: Config
metadata:
  name: vulnerabilitytracer
build:
  local:
    useBuildkit: true
  artifacts:
    - image: vulnerabilitytracer-coordinator
      context: .
      docker:
        target: coordinator-runtime
        dockerfile: Dockerfile-vulnerabilitytracer
    - image: vulnerabilitytracer-manager
      context: .
      docker:
        target: manager-runtime
        dockerfile: Dockerfile-vulnerabilitytracer
    - image: vulnerabilitytracer-dashboard
      context: .
      docker:
        dockerfile: Dockerfile-dashboard
manifests:
  kustomize:
    paths:
      - kube-manifests/vulnerabilitytracer
      - vulnerabilitytracer-service/db
deploy:
  kubectl: {}