# nonk8s
apiVersion: skaffold/v3
kind: Config
metadata:
  name: microservices
build:
  local:
    useBuildkit: true
  artifacts:
    - image: downstream-caller-service
      context: .
      docker:
        target: downstreamcallerservice
    - image: generator-service
      context: .
      docker:
        target: generatorservice
manifests:
  kustomize:
    paths:
      - kube-manifests/microservices
deploy:
  kubectl: {}