version: 3

vars:
  KUBE_DIR: "{{.ROOT_DIR}}/.kube"
  KUBECONFIG: "{{.KUBE_DIR}}/config"

env:
  KUBECONFIG: "{{.KUBECONFIG}}"

includes:
  cluster:
    taskfile: ./cluster
    dir: ./cluster
  telepresence:
    taskfile: ./Taskfile-telepresence.yml
    vars:
      KUBE_NAMESPACE: "vulnerabilitytracer"
  opentelemetry:
    taskfile: ./Taskfile-skaffold.yml
    vars:
      SKAFFOLD_FILE: "skaffold-opentelemetry.yaml"
  vulnerabilitytracer:
    taskfile: ./Taskfile-skaffold.yml
    vars:
      SKAFFOLD_FILE: "skaffold-vulnerabilitytracer.yaml"
  experiment:
    taskfile: ./Taskfile-experiment.yml

tasks:
  default:
    desc: "Start the local Kubernetes cluster, deploy the developed solution and the experimental setup"
    cmds:
      - task: cluster:create
      - task: run
      - task: experiment:run

  run:
    desc: "Deploy Vulnerability Tracer components to the cluster"
    cmds:
      - task: opentelemetry:run
      - task: vulnerabilitytracer:run

  delete:
    desc: "Remove Vulnerability Tracer components from the cluster"
    cmds:
      - task: vulnerabilitytracer:delete
      - task: opentelemetry:delete

  clean:
    desc: "Remove the local Kubernetes cluster and all of its data"
    cmds:
      - task: cluster:clean