version: 3

vars:
  SKAFFOLD_FILE: "{{ .SKAFFOLD_FILE }}"
  SKAFFOLD_ARGS: '{{ .SKAFFOLD_ARGS | default .CLI_ARGS }}'

tasks:
  run: "skaffold run --cache-artifacts=false --filename {{ .SKAFFOLD_FILE }} {{ .SKAFFOLD_ARGS }}"
  build: "skaffold build --cache-artifacts=false --filename {{ .SKAFFOLD_FILE }} {{ .SKAFFOLD_ARGS }}"
  debug: "skaffold debug --cache-artifacts=false --filename {{ .SKAFFOLD_FILE }} --tail=false {{ .SKAFFOLD_ARGS }}"
  delete: "skaffold delete --filename {{ .SKAFFOLD_FILE }} {{ .SKAFFOLD_ARGS }}"