version: 3

vars:
  KUBE_DIR: "{{.ROOT_DIR}}/.kube"
  KUBECONFIG: "{{.KUBE_DIR}}/config"

env:
  KUBECONFIG: "{{.KUBECONFIG}}"

includes:
  cluster:
    taskfile: ./cluster
    dir: ./cluster
  dev-container:
    taskfile: ./.devcontainer/Taskfile.yml
    aliases: [dc]
  microservices:
    taskfile: ./Taskfile-skaffold.yml
    vars:
      SKAFFOLD_FILE: "skaffold-microservices.yaml"
  loadgenerator:
    taskfile: ./Taskfile-skaffold.yml
    vars:
      SKAFFOLD_FILE: "skaffold-loadgenerator.yaml"
  opentelemetry:
    taskfile: ./Taskfile-skaffold.yml
    vars:
      SKAFFOLD_FILE: "skaffold-opentelemetry.yaml"
  vulnerabilitytracer:
    taskfile: ./Taskfile-skaffold.yml
    vars:
      SKAFFOLD_FILE: "skaffold-vulnerabilitytracer.yaml"
  telepresence:
    taskfile: ./Taskfile-telepresence.yml
    vars:
      KUBE_NAMESPACE: "vulnerabilitytracer"

tasks:
  default:
    cmds:
      - task: run

  run:
    cmds:
      - task: opentelemetry:run
      - task: vulnerabilitytracer:run
      - task: microservice:run
      - task: loadgenerator:run

  delete:
    cmds:
      - task: loadgenerator:delete
      - task: microservice:delete
      - task: vulnerabilitytracer:delete
      - task: opentelemetry:delete