version: 3

vars:
  KUBE_DIR: "{{.ROOT_DIR}}/.kube"
  KUBECONFIG: "{{.KUBE_DIR}}/config"

env:
  KUBECONFIG: "{{.KUBECONFIG}}"

includes:
  cluster:
    taskfile: ./cluster
    dir: ./cluster

tasks:
  run: "skaffold run"
  delete: "skaffold delete"
  # TODO: Replace with Locust
  generate-trace-data:
    cmds:
      - 'for i in $(seq 1 100); do curl -s -o /dev/null "http://alpha.localhost:8080/one"; curl -s -o /dev/null "http://alpha.localhost:8080/two"; done'
      - 'for i in $(seq 1 100); do curl -s -o /dev/null "http://beta.localhost:8080/one"; curl -s -o /dev/null "http://beta.localhost:8080/two"; done'
      - 'for i in $(seq 1 100); do curl -s -o /dev/null "http://gamma.localhost:8080/one"; curl -s -o /dev/null "http://gamma.localhost:8080/two"; done'
