version: 3

vars:
  KUBE_DIR: "{{.ROOT_DIR}}/.kube"
  KUBECONFIG: "{{.KUBE_DIR}}/config"

env:
  KUBECONFIG: "{{.KUBECONFIG}}"

includes:
  cluster:
    taskfile: ./cluster
    dir: ./cluster

tasks:
  default:
    cmds:
      - task: run

  run:
    cmds:
      - task: opentelemetry:run
      - task: microservice:run
      - task: loadgenerator:run

  delete:
    cmds:
      - task: loadgenerator:delete
      - task: microservice:delete
      - task: opentelemetry:delete

  opentelemetry:run: "skaffold run --filename skaffold-opentelemetry.yaml"
  opentelemetry:delete: "skaffold delete --filename skaffold-opentelemetry.yaml"

  microservice:run: "skaffold run"
  microservice:debug: "skaffold debug --tail=false"
  microservice:delete: "skaffold delete"

  loadgenerator:run: "skaffold run --filename skaffold-loadgenerator.yaml"
  loadgenerator:delete: "skaffold delete --filename skaffold-loadgenerator.yaml"
