version: 3

vars:
  KUBE_DIR: "{{.ROOT_DIR}}/.kube"
  KUBECONFIG: "{{.KUBE_DIR}}/config"

env:
  KUBECONFIG: "{{.KUBECONFIG}}"

includes:
  cluster:
    taskfile: ./cluster
    dir: ./cluster

tasks:
  default:
    cmds:
      - task: run

  run: "skaffold run"
  debug: "skaffold debug"
  delete: "skaffold delete"

  loadgenerator:run: "skaffold run --filename skaffold-loadgenerator.yaml"
  loadgenerator:delete: "skaffold delete --filename skaffold-loadgenerator.yaml"