version: 3

vars:
  SKAFFOLD_FILE: "{{ .SKAFFOLD_FILE }}"

tasks:
  run: "skaffold run --cache-artifacts=false --filename {{ .SKAFFOLD_FILE }}"
  build: "skaffold build --cache-artifacts=false --filename {{ .SKAFFOLD_FILE }}"
  debug: "skaffold debug --cache-artifacts=false --filename {{ .SKAFFOLD_FILE }} --tail=false"
  delete: "skaffold delete --filename {{ .SKAFFOLD_FILE }}"