version: 3

vars:
  PACKAGE_NAME: "{{.PACKAGE_NAME}}"

tasks:
  run:
    desc: "Run the application"
    cmds: [ "go run {{.PACKAGE_NAME}} {{.CLI_ARGS}}" ]
  build:
    desc: "Build the application"
    env:
      CGO_ENABLED: 0
    cmds:
      - task: :create-output-bin-dir
      - "go build -v -o {{.OUTPUT_BIN_DIR}} {{.PACKAGE_NAME}} {{.CLI_ARGS}}"