version: 3

vars:
  VENV_DIR: "./venv"
  PIP_BIN: "{{.VENV_DIR}}/bin/pip"
  PYTHON_BIN: "{{.VENV_DIR}}/bin/python"

  TRACECOLLECTOR_PACKAGE_DIR: "tracecollector"

tasks:
  tracecollector:run: "{{.PYTHON_BIN}} -m tracecollector {{.CLI_ARGS}}"
  tracecollector:test: "{{.PYTHON_BIN}} -m pytest -p no:cacheprovider {{.TRACECOLLECTOR_PACKAGE_DIR}}"

  venv:create:
    status: ["test -d {{.VENV_DIR}}"]
    cmds: ["python -m venv {{.VENV_DIR}}"]
  venv:prepare:
    deps: [venv:create]
    cmds:
      - "{{.PIP_BIN}} install --upgrade pip wheel"
      - "{{.PIP_BIN}} install -r requirements.txt"
  venv:clean:
    status: ["test ! -d {{.VENV_DIR}}"]
    cmds:
      - "rm -rf {{.VENV_DIR}}"


