version: 3

vars:
  DATABASE_URL: "postgres://vulnerabilitytracer:vulnerabilitytracer@localhost:5432/vulnerabilitytracer?sslmode=disable"
  DEV_DATABASE_URL: "docker://postgres/15.3"

tasks:
  fmt:
    cmds:
      - "atlas schema fmt ./schema"
  inspect:
    cmds:
      - >
        atlas schema inspect 
        --url "{{ .DATABASE_URL }}"
  diff:
    cmds:
      - >
        atlas schema diff 
        --to "file://schema" 
        --from "{{ .DATABASE_URL }}"
        --dev-url "{{ .DEV_DATABASE_URL }}"
  clean:
    cmds:
      - >
        atlas schema clean 
        --url "{{ .DATABASE_URL }}"
  apply:
    cmds:
      - > 
        atlas schema apply 
        --to "file://schema" 
        --url "{{ .DATABASE_URL }}"
        --dev-url "{{ .DEV_DATABASE_URL }}"
      - task: generate-sql
  generate-sql:
    cmds:
      - >
        atlas schema inspect 
        --url "{{ .DATABASE_URL }}"
        --format "{{ `{{ sql . }}` }}"
        > ./schema/schema.gen.sql
