version: 3

vars:
  ATLAS_ENV: '{{ .ATLAS_ENV | default "dev" }}'

tasks:
  fmt: "atlas schema fmt ./schema"
  inspect: "atlas schema inspect --env {{ .ATLAS_ENV }}"
  diff: "atlas schema diff --env {{ .ATLAS_ENV }}"
  clean: "atlas schema clean --env {{ .ATLAS_ENV }}"
  apply: "atlas schema apply --env {{ .ATLAS_ENV }}"

  generate:
    cmds:
      - task: generate-sql
      - task: generate-queries
  generate-sql: 'atlas schema inspect --env {{ .ATLAS_ENV }} --format "{{ `{{ sql . }}` }}" > ./generated/schema.gen.sql'
  generate-queries:
    cmds:
      - "rm -f ./generated/queries/*.go"
      - "sqlc generate"