version: 3

vars:
  DATABASE_URL: "postgres://vulnerabilitytracer:vulnerabilitytracer@localhost:5432/vulnerabilitytracer?sslmode=disable"

tasks:
  fmt:
    cmds:
      - "atlas schema fmt ./schema"
  migrate:
    cmds:
      - > 
        atlas schema apply 
        --to "file://schema" 
        --url "{{ .DATABASE_URL }}"
        --dev-url "docker://postgres/15.3"
  clean:
    cmds:
      - >
        atlas schema clean 
        --url "{{ .DATABASE_URL }}"
  diff:
    cmds:
      - >
        atlas schema diff 
        --to "file://schema" 
        --from "{{ .DATABASE_URL }}"
        --dev-url "docker://postgres/15.3"

  inspect:
    cmds:
      - >
        atlas schema inspect 
        --url "{{ .DATABASE_URL }}"
