version: 3

vars:
  ATLAS_ENV: '{{ .ATLAS_ENV | default "dev" }}'

tasks:
  fmt: "atlas schema fmt ./schema"
  inspect: "atlas schema inspect --env {{ .ATLAS_ENV }}"
  diff: "atlas schema diff --env {{ .ATLAS_ENV }}"
  clean: "atlas schema clean --env {{ .ATLAS_ENV }}"
  apply:
    cmds:
      - "atlas schema apply --env {{ .ATLAS_ENV }}"
      - task: generate-sql
  generate-sql: "atlas schema inspect --env {{ .ATLAS_ENV }} --format "{{ `{{ sql . }}` }}" > ./schema.gen.sql"
