kind: VirtualService
apiVersion: networking.istio.io/v1beta1
metadata:
  name: minio
spec:
  gateways:
    - minio-gateway
  hosts:
    - 'console.minio.localhost'
  http:
    - route:
        - destination:
            host: minio-console.minio.svc.cluster.local
            port:
              number: 9001