apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: minio
spec:
  namespaceSelector:
    matchNames:
      - minio
  endpoints:
    - path: /minio/v2/metrics/node
      port: http
      scheme: http
    - path: /minio/v2/metrics/bucket
      port: http
      scheme: http
  selector:
    matchLabels:
      app: minio
      monitoring: "true"
