apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: microservice
resources:
  - resources/istio-gateway.yaml
  - resources/namespace.yaml
  - resources/microservice-alpha.yaml
  - resources/microservice-beta.yaml
  - resources/microservice-gamma.yaml