run:
  allow-parallel-runners: true
  skip-files:
    - "wire_gen.go"
    - ".*\\.gen\\.go$"
  skip-dirs:
    - "generated"

linters:
  enable-all: true
  disable:
    # Deprecated linters
    - interfacer
    - golint
    - deadcode
    - ifshort
    - structcheck
    - varcheck
    - scopelint
    - nosnakecase
    - exhaustivestruct
    - maligned
    # exhaustruct disabled to not bother about not providing fields in structs
    - exhaustruct
    # we use goimport instead of gci
    - gci
    - depguard
