version: 3

vars:
  OUTPUT_DIR: "out"
  OUTPUT_BIN_DIR: "{{.OUTPUT_DIR}}/bin"

includes:
  dev: ./dev
  db:
    taskfile: ./db
    dir: ./db
  coordinator:
    taskfile: ./cmd/Taskfile.yml
    vars:
      PACKAGE_NAME: "vulnerabilitytracer/cmd/coordinator"
  manager:
    taskfile: ./cmd/Taskfile.yml
    vars:
      PACKAGE_NAME: "vulnerabilitytracer/cmd/manager"

tasks:
  mod-tidy:
    desc: "Run go mod tidy to clean up go.mod and go.sum"
    cmds: [ "go mod tidy" ]
  lint:
    desc: "Run the linter suite"
    cmds:
      - "golangci-lint run {{.CLI_ARGS}}"
  fmt:
    desc: "Format the code and cleanup imports in the Go code"
    cmds:
      - "goimports -w ."
      - "gofumpt -l -w ."
  generate:
    desc: "Run utilities to generate Go code. Make sure that development containers are running."
    cmds:
      - "go generate ./..."
      - task: db:generate
  build:
    cmds:
      - task: coordinator:build
      - task: manager:build
  clean:
    cmds: [ "rm -rf {{.OUTPUT_DIR}}" ]

  # Internal helper tasks
  create-output-dir:
    internal: true
    run: once
    cmds: [ "mkdir -p {{.OUTPUT_DIR}}" ]
  create-output-bin-dir:
    internal: true
    run: once
    cmds:
      - task: create-output-dir
      - "mkdir -p {{.OUTPUT_BIN_DIR}}"