version: 3

includes:
  dev: ./dev
  db:
    taskfile: ./db
    dir: ./db

tasks:
  mod-tidy:
    desc: "Run go mod tidy to clean up go.mod and go.sum"
    cmds: [ "go mod tidy" ]
  lint:
    desc: "Run the linter suite"
    cmds:
      - "golangci-lint run {{.CLI_ARGS}}"
  fmt:
    desc: "Format the code and cleanup imports in the Go code"
    cmds:
      - "goimports -w ."
      - "gofumpt -l -w ."
  generate:
    desc: "Run utilities to generate Go code"
    cmds: [ "go generate ./..." ]