server:
  port: 8000

management:
  server:
    port: 9000

downstream:
  firstUrl: "http://localhost:8000/terminus"
  secondUrl: "http://localhost:8000/terminus"

logging:
  pattern:
    level: "trace_id=%mdc{trace_id} span_id=%mdc{span_id} trace_flags=%mdc{trace_flags} %5p"