---
##### Application namespaces
---
apiVersion: v1
kind: Namespace
metadata:
  name: vulnerabilitytracer
---
apiVersion: v1
kind: Namespace
metadata:
  name: microservices
---
apiVersion: v1
kind: Namespace
metadata:
  name: loadgenerator