openapi: 3.0.3
info:
  title: FASTEN Project API
  description: FASTEN Project API
  version: 1.0.0
servers:
  - url: 'http://localhost:9080'
    description: Local deployment
  - url: 'https://api.fasten-project.eu'
    description: Production deployment
paths:
  /api/mvn/packages/{groupId}:{artifactId}/{version}:
    get:
      summary: Package details
      description: >
        Get details about the package version.
        If FASTEN doesn't know about it, it will add it to the processing queue.
      parameters:
        - name: groupId
          in: path
          required: true
          description: The group ID of the package's Maven coordinates
          schema:
            type: string
            example: "org.apache.logging.log4j"
        - name: artifactId
          in: path
          required: true
          description: The artifact ID of the package's Maven coordinates
          schema:
            type: string
            example: "log4j-core"
        - name: version
          in: path
          required: true
          description: The version of the package's Maven coordinates
          schema:
            type: string
            example: "2.17.0"
      responses:
        200:
          description: Details about the package version
        201:
          description: Package version was added to the processing queue

  /api/mvn/packages/{groupId}:{artifactId}/{version}/vulnerabilities:
    get:
      summary: Package vulnerabilities
      description: >
        Get information about package's vulnerabilities.
        Optionally limit the amount of returned parameters by specifying the "attributes" query parameter.
      parameters:
        - name: groupId
          in: path
          required: true
          description: The group ID of the package's Maven coordinates
          schema:
            type: string
            example: "org.apache.logging.log4j"
        - name: artifactId
          in: path
          required: true
          description: The artifact ID of the package's Maven coordinates
          schema:
            type: string
            example: "log4j-core"
        - name: version
          in: path
          required: true
          description: The version of the package's Maven coordinates
          schema:
            type: string
            example: "2.17.0"
        - name: attributes
          in: query
          required: false
          description: Comma-separated list of attributes to fetch. Leave empty to fetch all.
          schema:
            type: string
            example: "id"
      responses:
        200:
          description: List of package's vulnerabilities, with optional attributes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PackageVulnerability'

  /api/mvn/vulnerabilities/{vulnerabilityExternalId}/callables:
    get:
      summary: Vulnerable callables
      description: Get the list of callables affected by the vulnerability.
      parameters:
        - name: vulnerabilityExternalId
          in: path
          required: true
          description: The vulnerability external identifier (usually the CVE identifier)
          schema:
            type: string
            example: "CVE-2020-10683"
      responses:
        200:
          description: Map of callable identifiers to their FASTEN URIs
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: string

  /api/mvn/callables:
    post:
      summary: Callable details
      description: Get the list of callables affected by the vulnerability.
      requestBody:
        content:
          application/json:
            example: [433480]
            schema:
              type: array
              items:
                type: integer
      responses:
        200:
          description: Callable details
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  $ref: "#/components/schemas/Callable"

components:
  schemas:
    PackageVulnerability:
      title: Package vulnerability response
      type: object
      required:
        - id
        - external_id
        - statement
      properties:
        id:
          type: integer
          description: The vulnerability's identifier within FASTEN database
        external_id:
          type: string
          description: The vulnerability's external identifier (usually CVE)
        statement:
          type: object
          description: The vulnerability's attributes
    Callable:
      title: Vulnerable callable response
      type: object
      required:
        - is_internal_call
        - fasten_uri
        - metadata
      properties:
        is_internal_call:
          type: boolean
          description: The vulnerability's identifier within FASTEN database
        fasten_uri:
          type: string
          description: FASTEN URI (without schema)
        metadata:
          $ref: "#/components/schemas/CallableMetadata"
    CallableMetadata:
      title: Metadata of the vulnerable callable
      type: object
      properties:
        quality:
          $ref: "#/components/schemas/CallableQuality"
        vulnerabilities:
          additionalProperties:
            type: object
    CallableQuality:
      title: Vulnerable callable response
      type: object
      required:
        - callable_name
      properties:
        callable_name:
          type: string
          description: Name of the callable