openapi: 3.0.3
info:
  title: Vulnerability Tracer Service
  description: Vulnerability Tracer Service
  version: 0.1.0
servers:
  - url: 'http://localhost:10420'
paths:
  /liveness:
    get:
      summary: Check server liveness
      description: > 
        Liveness endpoint is used by Kubernetes to determine 
        if the application after startup is still able to serve the requests
      responses:
        200:
          description: Application is running
  /readiness:
    get:
      summary: Check server readiness
      description: >
        Readiness endpoint is used by Kubernetes to determine 
        if the application finished startup and can serve requests
      responses:
        200:
          description: Application can serve requests



  
