apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-epsilon
spec:
  template:
    metadata:
      annotations:
        instrumentation.opentelemetry.io/inject-java: "opentelemetry/vulnerabilitytracing-instrumentation"
    spec:
      containers:
        - name: generator-service
          env:
            - name: GENERATOR_ENABLED
              value: "false"