# Run from the project's root as the working directory for Compose

services:
  postgres:
    image: postgres:15.3
    ports:
      - "127.0.0.1:15432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./dev/postgres/init:/docker-entrypoint-initdb.d:ro
    environment:
      POSTGRES_PASSWORD: "postgres"

volumes:
  postgres-data: {}
