apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-epsilon2
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/proxyCPU: "1"
        sidecar.istio.io/proxyCPULimit: "1"
        sidecar.istio.io/proxyMemory: 256Mi
        sidecar.istio.io/proxyMemoryLimit: 256Mi
    spec:
      containers:
        - name: microservice
          env:
            - name: GENERATOR_ENABLED
              value: "true"
          resources:
            requests:
              cpu: "1"
              memory: 1024Mi
            limits:
              cpu: "1"
              memory: 1024Mi