apiVersion: batch/v1
kind: Job
metadata:
  name: vulnerabilitytracer-schema-apply
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      activeDeadlineSeconds: 120
      restartPolicy: OnFailure
      containers:
        - name: dev-db
          image: postgres:15.3
          env:
            - name: POSTGRES_DB
              value: dev
            - name: POSTGRES_USER
              value: dev
            - name: POSTGRES_PASSWORD
              value: dev
          ports:
            - containerPort: 5432
        - name: vulnerabilitytracer-schema
          image: vulnerabilitytracer-schema
          command:
            - /bin/sh
            - -c
            - >-
              /atlas schema apply --auto-approve
              --to file:///schema
              --url postgres://$DIST_USER:$DIST_PASSWORD@$DIST_HOST:$DIST_PORT/$DIST_DATABASE
              --dev-url postgres://dev:dev@localhost:5432/dev?sslmode=disable
          env:
            - name: DIST_HOST
              valueFrom:
                secretKeyRef:
                  name: vulnerabilitytracer-db-app
                  key: host
            - name: DIST_USER
              valueFrom:
                secretKeyRef:
                  name: vulnerabilitytracer-db-app
                  key: user
            - name: DIST_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: vulnerabilitytracer-db-app
                  key: password
            - name: DIST_PORT
              valueFrom:
                secretKeyRef:
                  name: vulnerabilitytracer-db-app
                  key: port
            - name: DIST_DATABASE
              valueFrom:
                secretKeyRef:
                  name: vulnerabilitytracer-db-app
                  key: dbname
