apiVersion: apps/v1
kind: Deployment
metadata:
  name: vulnerabilitytracer-manager
  labels:
    app: vulnerabilitytracer-manager
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vulnerabilitytracer-manager
      version: v1
  template:
    metadata:
      labels:
        app: vulnerabilitytracer-manager
        version: v1
    spec:
      containers:
        - image: vulnerabilitytracer-manager
          name: manager
          env:
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: vulnerabilitytracer-db-app
                  key: user
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: vulnerabilitytracer-db-app
                  key: password
            - name: DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: vulnerabilitytracer-db-app
                  key: host
            - name: DATABASE_PORT
              valueFrom:
                secretKeyRef:
                  name: vulnerabilitytracer-db-app
                  key: port
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: vulnerabilitytracer-db-app
                  key: dbname
          envFrom:
            - configMapRef:
                name: vulnerabilitytracer-manager-config
          ports:
            - name: http
              containerPort: 11420
          livenessProbe:
            httpGet:
              path: /liveness
              port: http
            initialDelaySeconds: 5
          readinessProbe:
            httpGet:
              path: /readiness
              port: http
            initialDelaySeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: vulnerabilitytracer-manager
  labels:
    app: vulnerabilitytracer-manager
    version: v1
spec:
  ports:
    - name: http
      port: 11420
  selector:
    app: vulnerabilitytracer-manager
    version: v1
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vulnerabilitytracer-manager-config
  labels:
    app: vulnerabilitytracer-manager-config
    version: v1
data:
  LOG_LEVEL: "INFO"
---
kind: VirtualService
apiVersion: networking.istio.io/v1beta1
metadata:
  name: vulnerabilitytracer-manager
spec:
  gateways:
    - vulnerabilitytracer-gateway
  hosts:
    - 'manager.vulnerabilitytracer.localhost'
  http:
    - route:
        - destination:
            host: vulnerabilitytracer-manager.vulnerabilitytracer.svc.cluster.local
