apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-epsilon1
spec:
  template:
    spec:
      containers:
        - name: generator-service
          env:
            - name: GENERATOR_ENABLED
              value: "false"