apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgenerator-epsilon
  labels:
    app: loadgenerator-epsilon
    version: v1
spec:
  template:
    spec:
      containers:
        - name: loadgenerator
          image: loadgenerator
          env:
            - name: LOADGENERATOR_SERVICE_ADDR_ONE
              value: "http://microservice-epsilon-basic:8000/int"
            - name: LOADGENERATOR_SERVICE_ADDR_TWO
              value: "http://microservice-epsilon-collecting:8000/int"
            - name: LOADGENERATOR_INTERVAL_MS
              value: "100"
