apiVersion: v1
kind: Service
metadata:
  name: microservice-epsilon
  labels:
    app: microservice-epsilon
    version: v1
spec:
  ports:
    - name: http
      port: 8000
  selector:
    thesis.ponichtera.dev/experiment-app: microservice-epsilon
    version: v1
