apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: microservices
spec:
  namespaceSelector:
    matchNames:
      - experiment
  jobLabel: "app"
  selector:
    matchExpressions:
      - key: "app"
        operator: "In"
        values:
          - "microservice-epsilon-basic"
          - "microservice-epsilon-collecting"
  podMetricsEndpoints:
    - port: metrics
      path: "/actuator/prometheus"

