kind: VirtualService
apiVersion: networking.istio.io/v1beta1
metadata:
  name: grafana
spec:
  gateways:
    - lgtm-gateway
  hosts:
    - 'grafana.lgtm.localhost'
  http:
    - route:
        - destination:
            host: kiali.istio-system.svc.cluster.local
