apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
#  - opentelemetry-collector.yaml
  #  - opentelemetry-operator.yaml
  #  - lgtm-stack.yaml
  - istio-gateway.yaml
  - istio-virtualservices.yaml
