apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: demo
  hub: docker.io/istio
  tag: 1.20.2
  meshConfig:
    enableTracing: true
    defaultConfig:
      # Using canonical service name so that it matches OpenTelemetry instrumentation one
      tracingServiceName: CANONICAL_NAME_ONLY
      tracing:
        sampling: 100
        zipkin:
          address: traces-collector.opentelemetry.svc.cluster.local:9411
  components:
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        k8s:
          service:
            ports:
              - name: status-port
                port: 15021
                targetPort: 15021
              - name: http2
                port: 80
                targetPort: 8080
              - name: https
                port: 443
                targetPort: 8443
              - name: postgres
                port: 25432
                targetPort: 25432
