# nonk8s
apiVersion: k3d.io/v1alpha4
kind: Simple

servers: 1
agents: 3

ports:
  - port: 8080:80
    nodeFilters:
      - loadbalancer
  - port: 8443:443
    nodeFilters:
      - loadbalancer

registries:
  use:
    - k3d-thesis-registry-docker-io:5000
  config: |
    mirrors:
      "docker.io":
        endpoint:
          - "http://k3d-thesis-registry-docker-io:5000"

options:
  k3s:
    extraArgs:
      - arg: "--disable=traefik"
        nodeFilters:
          - "server:*"
      - arg: "--node-taint=k3s-controlplane=true:NoExecute"
        nodeFilters:
          - "server:*"
  kubeconfig:
    updateDefaultKubeconfig: false
    switchCurrentContext: false