# nonk8s
apiVersion: k3d.io/v1alpha4
kind: Simple

servers: 1
agents: 1

ports:
  - port: 8080:80
    nodeFilters:
      - loadbalancer
  - port: 8443:443
    nodeFilters:
      - loadbalancer
  - port: 25432:25432
    nodeFilters:
      - loadbalancer

registries:
  use:
    - k3d-thesis-registry-local:5000
    - k3d-thesis-registry-docker-io:5000
    - k3d-thesis-registry-quay-io:5000
    - k3d-thesis-registry-ghcr-io:5000
  config: |
    mirrors:
      "localhost:5000":
        endpoint:
          - "http://k3d-thesis-registry-local:5000"
      "docker.io":
        endpoint:
          - "http://k3d-thesis-registry-docker-io:5000"
      "quay.io":
        endpoint:
          - "http://k3d-thesis-registry-quay-io:5000"
      "ghcr.io":
        endpoint:
          - "http://k3d-thesis-registry-ghcr-io:5000"

options:
  k3s:
    extraArgs:
      - arg: "--disable=traefik"
        nodeFilters:
          - "server:*"
      - arg: "--node-taint=k3s-controlplane=true:NoExecute"
        nodeFilters:
          - "server:*"
      - arg: "--kubelet-arg=cpu-manager-policy=static"
        nodeFilters:
          - "agent:*"
      - arg: "--kubelet-arg=kube-reserved=cpu=512m,memory=256Mi"
        nodeFilters:
          - "agent:*"
      - arg: "--kubelet-arg=enforce-node-allocatable=pods"
        nodeFilters:
          - "agent:*"
  kubeconfig:
    updateDefaultKubeconfig: false
    switchCurrentContext: false