version: 3

vars:
  CLUSTER_NAME: "thesis"

env:
  CLUSTER_NAME: "{{.CLUSTER_NAME}}"

includes:
  # TASKFILE BUG: nested include vars do not work
  registry-local:
    internal: true
    taskfile: ./Taskfile-registry-local.yml
  registry-docker-io:
    internal: true
    taskfile: ./Taskfile-registry-docker-io.yml
  registry-quay-io:
    internal: true
    taskfile: ./Taskfile-registry-quay-io.yml

tasks:
  ##### Cluster management
  create:
    cmds:
      - task: registry:create
      - "k3d cluster create {{.CLUSTER_NAME}} --config k3d_cluster.yml"
      - "k3d kubeconfig merge {{.CLUSTER_NAME}} --output={{.KUBECONFIG}}"
      - task: istio:install
    status:
      - "test -f {{.KUBECONFIG}}"
      - "k3d cluster list {{.CLUSTER_NAME}}"
  start:
    cmds:
      - task: registry:create
      - "k3d cluster start {{.CLUSTER_NAME}}"
  stop:
    cmds:
      - "k3d cluster stop {{.CLUSTER_NAME}}"
      - task: registry:delete
  delete:
    cmds:
      - "k3d cluster delete {{.CLUSTER_NAME}}"
      - "rm -rf {{.KUBECONFIG}}"
      - task: registry:delete
    status:
      - "! test -f {{.KUBECONFIG}}"
      - "! k3d cluster list {{.CLUSTER_NAME}}"
  clean:
    cmds:
      - task: delete
      - task: registry:clean
      - "rm -rf {{.KUBE_DIR}}"
  ##### K3D Registry management
  registry:create:
    cmds:
      - task: registry-local:create
      - task: registry-docker-io:create
      - task: registry-quay-io:create
  registry:delete:
    cmds:
      - task: registry-local:delete
      - task: registry-docker-io:delete
      - task: registry-quay-io:delete
  registry:clean:
    cmds:
      - task: registry:delete
      - task: registry-local:clean
      - task: registry-docker-io:clean
      - task: registry-quay-io:clean
  ##### Istio management
  istio:install:
    cmds:
      - "istioctl install --set profile=demo -y"
      - "kubectl apply -f istio_addons"
  istio:jaeger: "istioctl dashboard jaeger"
  istio:kiali: "istioctl dashboard kiali"
  istio:prometheus: "istioctl dashboard prometheus"
  istio:grafana: "istioctl dashboard grafana"