version: 3

tasks:
  default:
    cmds:
      - task: istio
      - task: cert-manager
      - task: opentelemetry-operator
      - task: minio
      - task: prometheus
      - task: lgtm-stack
      - task: apply
  lgtm-stack:
    cmds:
      - task: grafana-loki
      - task: grafana-promtail
      - task: grafana-tempo
      - task: grafana-mimir
      - task: grafana
  ##### Istio
  istio: "istioctl install -f istio.yaml -y"
  ##### Cluster applications
  cert-manager: >-
    helm upgrade cert-manager cert-manager
    --repo https://charts.jetstack.io
    --version v1.11.0
    --namespace cert-manager
    --set installCRDs=true
    --create-namespace
    --install
    --atomic
  opentelemetry-operator: >-
    helm upgrade opentelemetry-operator opentelemetry-operator
    --repo https://open-telemetry.github.io/opentelemetry-helm-charts
    --version v0.27.0
    --namespace opentelemetry
    --create-namespace
    --install
    --atomic
  minio: >-
    helm upgrade minio minio
    --repo https://charts.min.io/
    --version v5.0.8
    --namespace minio
    --values chart-values/minio.yaml
    --create-namespace
    --install
    --atomic
  prometheus: >-
    helm upgrade kube-prometheus-stack kube-prometheus-stack
    --repo https://prometheus-community.github.io/helm-charts
    --version v45.24.0
    --namespace lgtm
    --values chart-values/kube-prometheus-stack.yaml
    --create-namespace
    --install
    --atomic
  grafana-loki: >-
    helm upgrade loki loki
    --repo https://grafana.github.io/helm-charts
    --version v5.2.0
    --namespace lgtm
    --values chart-values/loki.yaml
    --create-namespace
    --install
    --atomic
  grafana-promtail: >-
    helm upgrade promtail promtail
    --repo https://grafana.github.io/helm-charts
    --version v6.11.0
    --namespace lgtm
    --values chart-values/promtail.yaml
    --create-namespace
    --install
    --atomic
  grafana-tempo: >-
    helm upgrade tempo tempo
    --repo https://grafana.github.io/helm-charts
    --version v1.1.0
    --namespace lgtm
    --values chart-values/tempo.yaml
    --create-namespace
    --install
    --atomic
  grafana-mimir: >-
    helm upgrade mimir mimir-distributed
    --repo https://grafana.github.io/helm-charts
    --version v4.3.1
    --namespace lgtm
    --values chart-values/mimir.yaml
    --create-namespace
    --install
    --atomic
  grafana:
    cmds:
      - "kubectl apply --kustomize chart-values/grafana-dashboards"
      - >-
        helm upgrade grafana grafana
        --repo https://grafana.github.io/helm-charts
        --version v6.56.1
        --namespace lgtm
        --values chart-values/grafana.yaml
        --create-namespace
        --install
        --atomic
  apply:
    cmds:
      - "kubectl apply --kustomize config/opentelemetry"
      - "kubectl apply --kustomize config/lgtm"
      - "kubectl apply --kustomize config/minio"
      - "kubectl apply --kustomize config/istio"
