version: 3

tasks:
  default:
    cmds:
      - task: namespaces
      - task: istio
      - task: kiali
      - task: cert-manager
      - task: opentelemetry-operator
      - task: prometheus
      - task: minio
      - task: lgtm-stack
      - task: postgres-operator
      - task: atlas-operator
      - task: telepresence
      - task: apply
  lgtm-stack:
    cmds:
      - task: grafana-loki
      - task: grafana-promtail
      - task: grafana-tempo
      - task: grafana-mimir
      - task: grafana
  ##### Namespaces (with necessary annotations)
  namespaces: "kubectl apply --kustomize namespaces"
  ##### Istio
  istio: "istioctl install -f istio.yaml -y"
  ##### Cluster applications
  kiali: >-
    helm upgrade kiali-server kiali-server
    --repo https://kiali.org/helm-charts
    --version 1.79.0
    --namespace istio-system
    --values chart-values/kiali.yaml
    --install
    --atomic
  cert-manager: >-
    helm upgrade cert-manager cert-manager
    --repo https://charts.jetstack.io
    --version 1.13.3
    --namespace cert-manager
    --set installCRDs=true
    --install
    --atomic
  opentelemetry-operator: >-
    helm upgrade opentelemetry-operator opentelemetry-operator
    --repo https://open-telemetry.github.io/opentelemetry-helm-charts
    --version 0.46.0
    --namespace opentelemetry
    --install
    --atomic
  minio: >-
    helm upgrade minio minio
    --repo https://charts.min.io/
    --version 5.0.15
    --namespace minio
    --values chart-values/minio.yaml
    --install
    --atomic
  prometheus: >-
    helm upgrade kube-prometheus-stack kube-prometheus-stack
    --repo https://prometheus-community.github.io/helm-charts
    --version 56.2.1
    --namespace lgtm
    --values chart-values/kube-prometheus-stack.yaml
    --install
    --atomic
  grafana-loki: >-
    helm upgrade loki loki
    --repo https://grafana.github.io/helm-charts
    --version 5.42.0
    --namespace lgtm
    --values chart-values/loki.yaml
    --install
    --atomic
  grafana-promtail: >-
    helm upgrade promtail promtail
    --repo https://grafana.github.io/helm-charts
    --version 6.15.4
    --namespace lgtm
    --values chart-values/promtail.yaml
    --install
    --atomic
  grafana-tempo: >-
    helm upgrade tempo tempo-distributed
    --repo https://grafana.github.io/helm-charts
    --version 1.8.2
    --namespace lgtm
    --values chart-values/tempo.yaml
    --install
    --atomic
  grafana-mimir: >-
    helm upgrade mimir mimir-distributed
    --repo https://grafana.github.io/helm-charts
    --version 5.2.1
    --namespace lgtm
    --values chart-values/mimir.yaml
    --install
    --atomic
  postgres-operator: >-
    helm upgrade cloudnative-pg cloudnative-pg
    --repo https://cloudnative-pg.github.io/charts
    --version 0.20.0
    --namespace postgres
    --install
    --atomic
  atlas-operator: >-
    helm upgrade atlas-operator oci://ghcr.io/ariga/charts/atlas-operator
    --version 0.3.8
    --namespace atlas-operator
    --set prewarmDevDB=false
    --install
    --atomic
  telepresence: >-
    helm upgrade traffic-manager telepresence
    --repo https://getambassador.io/
    --version 2.19.0-test.3
    --namespace telepresence
    --values chart-values/telepresence.yaml
    --install
    --atomic
  grafana:
    cmds:
      - "kubectl apply --kustomize chart-values/grafana-dashboards"
      - >-
        helm upgrade grafana grafana
        --repo https://grafana.github.io/helm-charts
        --version 7.2.5
        --namespace lgtm
        --values chart-values/grafana.yaml
        --install
        --atomic
  apply:
    cmds:
      - "kubectl apply --kustomize config/opentelemetry"
      - "kubectl apply --kustomize config/lgtm"
      - "kubectl apply --kustomize config/minio"
      - "kubectl apply --kustomize config/istio"
      - "kubectl apply --kustomize config/microservices"
      - "kubectl apply --kustomize config/vulnerabilitytracer"
      - "kubectl apply --kustomize config/vulnerabilitytracer-db"