version: 3

vars:
  KUBE_DIR: "{{.ROOT_DIR}}/.kube"
  KUBECONFIG: "{{.KUBE_DIR}}/config"
  CLUSTER_NAME: "thesis"

env:
  KUBECONFIG: "{{.KUBECONFIG}}"
  CLUSTER_NAME: "{{.CLUSTER_NAME}}"

includes:
  registry-docker-io:
    internal: true
    taskfile: ./Taskfile-registry.yml
    # TASKFILE BUG: nested include vars do not work
    vars:
      NAME: "{{.CLUSTER_NAME}}-registry-docker-io"
      PROXY_URL: "https://registry-1.docker.io"

tasks:
  ##### Cluster management
  create:
    cmds:
      - task: registry:create
      - "k3d cluster create {{.CLUSTER_NAME}} --config config.yml"
      - "k3d kubeconfig merge {{.CLUSTER_NAME}} --output={{.KUBECONFIG}}"
    status:
      - "test -f {{.KUBECONFIG}}"
      - "k3d cluster list {{.CLUSTER_NAME}}"
  start:
    cmds:
      - task: registry:create
      - "k3d cluster start {{.CLUSTER_NAME}}"
  stop:
    cmds:
      - "k3d cluster stop {{.CLUSTER_NAME}}"
      - task: registry:delete
  delete:
    cmds:
      - "k3d cluster delete {{.CLUSTER_NAME}}"
      - "rm -rf {{.KUBECONFIG}}"
      - task: registry:delete
    status:
      - "! test -f {{.KUBECONFIG}}"
      - "! k3d cluster list {{.CLUSTER_NAME}}"
  clean:
    cmds:
      - task: registry:clean
      - "rm -rf {{.KUBE_DIR}}"
  ##### K3D Registry management
  registry:create:
    cmds:
      - task: registry-docker-io:create
  registry:delete:
    cmds:
      - task: registry-docker-io:delete
  registry:clean:
    cmds:
      - task: registry:delete
      - task: registry-docker-io:clean
  ##### Istio management
  istio:install: "istioctl install --set profile=demo -y"