version: 3

vars:
  CLUSTER_NAME: "thesis"

env:
  CLUSTER_NAME: "{{.CLUSTER_NAME}}"

includes:
  # TASKFILE BUG: nested include vars do not work
  registry-local:
    internal: true
    taskfile: ./Taskfile-registry-local.yml
  registry-docker-io:
    internal: true
    taskfile: ./Taskfile-registry-docker-io.yml
  registry-quay-io:
    internal: true
    taskfile: ./Taskfile-registry-quay-io.yml
  registry-ghcr-io:
    internal: true
    taskfile: ./Taskfile-registry-ghcr-io.yml
  configure:
    taskfile: ./Taskfile-configure.yml

tasks:
  ##### Cluster management
  create:
    desc: "Create and configure local Kubernetes cluster"
    cmds:
      - task: registry:create
      - "k3d cluster create {{.CLUSTER_NAME}} --config k3d_cluster.yml"
      - "k3d kubeconfig merge {{.CLUSTER_NAME}} --output={{.KUBECONFIG}}"
      - task: configure
    status:
      - "test -f {{.KUBECONFIG}}"
      - "k3d cluster list {{.CLUSTER_NAME}}"
  start:
    desc: "Start local Kubernetes cluster and its container registries"
    cmds:
      - task: registry:start
      - "k3d cluster start {{.CLUSTER_NAME}}"
  stop:
    desc: "Stop local Kubernetes cluster and its container registries"
    cmds:
      - "k3d cluster stop {{.CLUSTER_NAME}}"
      - task: registry:stop
  delete:
    desc: "Delete local Kubernetes cluster and its container registries (without removing their cached images)"
    cmds:
      - "k3d cluster delete {{.CLUSTER_NAME}}"
      - "rm -rf {{.KUBECONFIG}}"
      - task: registry:delete
    status:
      - "! test -f {{.KUBECONFIG}}"
      - "! k3d cluster list {{.CLUSTER_NAME}}"
  clean:
    desc: "Delete local Kubernetes cluster, its container registries and their cached images"
    cmds:
      - task: delete
      - task: registry:clean
  ##### K3D Registry management
  registry:create:
    cmds:
      - task: registry-local:create
      - task: registry-docker-io:create
      - task: registry-quay-io:create
      - task: registry-ghcr-io:create
  registry:start:
    cmds:
      - task: registry-local:start
      - task: registry-docker-io:start
      - task: registry-quay-io:start
      - task: registry-ghcr-io:start
  registry:stop:
    cmds:
      - task: registry-local:stop
      - task: registry-docker-io:stop
      - task: registry-quay-io:stop
      - task: registry-ghcr-io:stop
  registry:delete:
    cmds:
      - task: registry-local:delete
      - task: registry-docker-io:delete
      - task: registry-quay-io:delete
      - task: registry-ghcr-io:delete
  registry:clean:
    cmds:
      - task: registry:delete
      - task: registry-local:clean
      - task: registry-docker-io:clean
      - task: registry-quay-io:clean
      - task: registry-ghcr-io:clean
  ##### Miscellaneous tasks
  database:recreate:
    desc: "Recreate database of Vulnerability Tracer"
    cmds:
      - "kubectl delete --kustomize config/vulnerabilitytracer-db"
      - "kubectl apply --kustomize config/vulnerabilitytracer-db"
  database:get-password:
    desc: "Get password to the database of Vulnerability Tracer"
    cmd: >- 
      kubectl  get secret vulnerabilitytracer-db-app 
      --namespace vulnerabilitytracer
      --output jsonpath='{.data.password}' 
      | base64 --decode
      ; echo
    
