apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgenerator-gamma
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loadgenerator-gamma
  template:
    metadata:
      labels:
        app: loadgenerator-gamma
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
    spec:
      terminationGracePeriodSeconds: 5
      containers:
        - name: locust
          image: loadgenerator
          env:
            - name: SERVICE_ADDR
              value: "microservice-gamma.microservices.svc.cluster.local:8000"
            - name: USERS
              value: "10"
          resources:
            requests:
              cpu: 300m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi