apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgenerator-beta
  labels:
    app: loadgenerator-beta
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loadgenerator-beta
      version: v1
  template:
    metadata:
      labels:
        app: loadgenerator-beta
        version: v1
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
    spec:
      terminationGracePeriodSeconds: 5
      containers:
        - name: locust
          image: loadgenerator
          env:
            - name: SERVICE_ADDR
              value: "microservice-beta.microservices.svc.cluster.local:8000"
          resources:
            requests:
              cpu: 300m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi