version: 3

vars: 
  CONTAINER_NAME: "tvd-platform-devcontainer"
  DOCKER_NETWORK_NAME: "tvd-platform-devcontainer-net"

tasks:
  default:
    cmds: [task: exec]

  build:
    cmd: "devcontainer build --workspace-folder ."

  create:
    desc: "Create and run dev container"
    cmd: "devcontainer up --workspace-folder ."

  recreate:
    desc: "Rebuilds and recreates dev container"
    cmds:
      - task: build
      - "devcontainer up --workspace-folder . --remove-existing-container"

  exec:
    desc: >-
      Runs command in dev container. Specify it after: "--". If no command specified a shell will be launched".
      Example: "task dc -- task generate".
    deps: [up]
    cmds:
      - 'devcontainer exec --workspace-folder . {{ .CLI_ARGS | default "/bin/bash" }}'
