apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-epsilon2
spec:
  template:
    metadata:
      annotations:
        instrumentation.opentelemetry.io/inject-java: "opentelemetry/vulnerabilitytracing-instrumentation"
