kind: VirtualService
apiVersion: networking.istio.io/v1beta1
metadata:
  name: grafana
spec:
  gateways:
    - lgtm-gateway
  hosts:
    - 'grafana.lgtm.localhost'
  http:
    - route:
        - destination:
            host: grafana.lgtm.svc.cluster.local
---
kind: VirtualService
apiVersion: networking.istio.io/v1beta1
metadata:
  name: tempo-query-frontend
spec:
  gateways:
    - lgtm-gateway
  hosts:
    - 'tempo.lgtm.localhost'
  http:
    - route:
        - destination:
            host: tempo-query-frontend.lgtm.svc.cluster.local
            port:
              number: 3100