apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: lgtm
resources:
  - istio-gateway.yaml
  - istio-virtualservices.yaml
#  - grafana-agent.yaml
#  - agent-control-plane/metrics-instance.yaml
#  - agent-control-plane/cadvisor-monitor.yaml
#  - agent-control-plane/kubelet-monitor.yaml
