apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: experiment
resources:
  - microservice-alpha.yaml
  - microservice-beta.yaml
  - microservice-gamma.yaml
  - microservice-epsilon1.yaml
  - microservice-epsilon2.yaml
  - loadgenerator-alpha.yaml
  - loadgenerator-beta.yaml
  - loadgenerator-gamma.yaml
  - pod-monitor.yaml

commonLabels:
  thesis.ponichtera.dev/experiment-type: qualitative
