apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgenerator-gamma
  labels:
    app: loadgenerator-gamma
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loadgenerator-gamma
      version: v1
  template:
    metadata:
      labels:
        app: loadgenerator-gamma
        version: v1
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
    spec:
      containers:
        - name: loadgenerator
          image: loadgenerator
          env:
            - name: LOADGENERATOR_SERVICE_ADDR_ONE
              value: "http://microservice-gamma:8000/one"
            - name: LOADGENERATOR_SERVICE_ADDR_TWO
              value: "http://microservice-gamma:8000/two"
            - name: LOADGENERATOR_INTERVAL_MS
              value: "1000"
          resources:
            requests:
              cpu: 300m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi