apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base

patchesStrategicMerge:
  - microservice-alpha.yaml
  - microservice-beta.yaml
  - microservice-gamma.yaml

commonLabels:
  thesis.ponichtera.dev/experiment-scenario: scenario1
