apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: vulnerabilitytracer-db
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:15.3
  instances: 1
  bootstrap:
    initdb:
      database: vulnerabilitytracer
      owner: vulnerabilitytracer
  storage:
    size: 10Gi
  monitoring:
    enablePodMonitor: true
---
kind: VirtualService
apiVersion: networking.istio.io/v1beta1
metadata:
  name: vulnerabilitytracer-db
spec:
  gateways:
    - vulnerabilitytracer-gateway
  hosts:
    - 'db.vulnerabilitytracer.localhost'
  tcp:
    - match:
        - port: 5432
      route:
        - destination:
            host: vulnerabilitytracer-db-rw.vulnerabilitytracer.svc.cluster.local
            port:
              number: 5432