# TODO: Doesn't work
kind: VirtualService
apiVersion: networking.istio.io/v1beta1
metadata:
  name: kiali
spec:
  gateways:
    - istio-gateway
  hosts:
    - 'kiali.istio.localhost'
  http:
    - route:
        - destination:
            host: kiali.istio-system.svc.cluster.local
