fullnameOverride: "prometheus"
cleanPrometheusOperatorObjectNames: true

grafana:
  enabled: false
  forceDeployDashboards: true

alertmanager:
  enabled: false

prometheus:
  prometheusSpec:
    ruleSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    probeSelectorNilUsesHelmValues: false
    remoteWriteDashboards: true
    remoteWrite:
      - name: mimir
        url: http://mimir-nginx.lgtm.svc.cluster.local/api/v1/push